# Generated by Django 5.0.6 on 2024-06-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('performers', models.CharField(max_length=100, null=True, verbose_name='Исполнители')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации задачи')),
                ('deadline', models.DateTimeField(null=True, verbose_name='Дата завершения задачи')),
                ('status', models.CharField(choices=[('Assigned', 'Назначена'), ('In progress', 'Выполняется'), ('Paused', 'Приостановлена'), ('Completed', 'Завершена')], max_length=100, verbose_name='Статус задачи')),
                ('planned_intensity', models.IntegerField()),
                ('actual_completion_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Подзадача',
                'verbose_name_plural': 'Подзадачи',
            },
        ),
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('performers', models.CharField(max_length=100, null=True, verbose_name='Исполнители')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации задачи')),
                ('deadline', models.DateTimeField(null=True, verbose_name='Дата завершения задачи')),
                ('status', models.CharField(choices=[('Assigned', 'Назначена'), ('In progress', 'Выполняется'), ('Paused', 'Приостановлена'), ('Completed', 'Завершена')], max_length=100, verbose_name='Статус задачи')),
                ('planned_intensity', models.IntegerField()),
                ('actual_completion_time', models.DateTimeField(null=True)),
                ('subtasks', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subtasks', to='tasks.subtask', verbose_name='Подзадачи')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
