# Generated by Django 5.0.6 on 2024-07-04 09:14

import core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=core.constants.Values["NAME_MAX_LENGTH"],
                        verbose_name=core.constants.Literals["TASK_NAME"],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        verbose_name=core.constants.Literals["DESCRIPTION"]
                    ),
                ),
                (
                    "performers",
                    models.CharField(
                        max_length=core.constants.Values["NAME_MAX_LENGTH"],
                        null=True,
                        verbose_name=core.constants.Literals["PERFORMERS"],
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name=core.constants.Literals["CREATED_AT"],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                core.constants.Literals["ASSIGNED_INTERNAL"],
                                core.constants.Literals["ASSIGNED_RU"],
                            ),
                            (
                                core.constants.Literals[
                                    "IN_PROGRESS_INTERNAL"
                                ],
                                core.constants.Literals["IN_PROGRESS_RU"],
                            ),
                            (
                                core.constants.Literals["PAUSED_INTERNAL"],
                                core.constants.Literals["PAUSED_RU"],
                            ),
                            (
                                core.constants.Literals["COMPLETED_INTERNAL"],
                                core.constants.Literals["COMPLETED_RU"],
                            ),
                        ],
                        default=core.constants.Literals["ASSIGNED_INTERNAL"],
                        max_length=core.constants.Values["NAME_MAX_LENGTH"],
                        verbose_name=core.constants.Literals["STATUS"],
                    ),
                ),
                (
                    "planned_intensity",
                    models.IntegerField(
                        verbose_name=core.constants.Literals[
                            "PLANNED_INTENSITY"
                        ]
                    ),
                ),
                (
                    "deadline",
                    models.DateTimeField(
                        null=True,
                        verbose_name=core.constants.Literals["DEADLINE"],
                    ),
                ),
                (
                    "actual_completion_time",
                    models.IntegerField(
                        help_text=core.constants.Literals[
                            "ACTUAL_COMPLETION_TIME_HELP_TEXT"
                        ],
                        verbose_name=core.constants.Literals[
                            "ACTUAL_COMPLETION_TIME"
                        ],
                    ),
                ),
                ("is_root_task", models.BooleanField(default=False)),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="tasks.taskmodel",
                        verbose_name=core.constants.Literals[
                            "SUBTASK_VERBOSE_NAME"
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": core.constants.Literals["TASK_VERBOSE_NAME"],
                "verbose_name_plural": core.constants.Literals[
                    "TASK_VERBOSE_NAME_PLURAL"
                ],
            },
        ),
    ]
